version: "3.3"

services:
  front-end:
    build: .
    restart: always
    networks:
      - backend
    environment:
      APP_ENV: dev
    ports:
      - "127.0.0.1:8080:3000"

networks:
  backend:
    external: true
